name: Install Project Dependencies
description: Install Project Dependencies

runs:
  using: 'composite'
  steps:
    - name: Setup Node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: yarn install
      shell: bash
      run: yarn install

    - name: yarn build
      shell: bash
      run: yarn build
