name: scrape-silent-all
on:
  workflow_dispatch:
  schedule:
    # run on 18:45 every Mon, Wed, Thurs, Sat, Sun
    - cron: '45 18 * * 0,1,3,4,6'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Build /dist
        run: yarn build

      - name: Scrape data from ALL sources
        env:
          NODE_ENV: production
        run: yarn start -s

      - name: Deploy to Github Pages
        uses:  JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          GIT_CONFIG_NAME: 'Lottery Scraper'
          FOLDER: temp/data
          CLEAN: true
          SINGLE_COMMIT: true
