name: scrape-test

on:
  workflow_dispatch:
    inputs:
      send_notification:
        required: true
        type: boolean
        default: true
        description: 'Send push notification after scraping'
      skip_notification_check:
        required: true
        type: boolean
        default: true
        description: 'Skip notification check for testing purposes'

jobs:
  general-setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      send_notification: ${{ steps.send_notification.outputs.SEND_NOTIFICATION }}
      skip_notification_check: ${{ steps.skip_notification_check.outputs.SKIP_NOTIFICATION_CHECK }}
    steps:
      - uses: actions/checkout@v4
      - name: Get send_notification variable
        id: send_notification
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "SEND_NOTIFICATION=${{ inputs.send_notification }}" >> $GITHUB_OUTPUT
          else
            echo "SEND_NOTIFICATION=true" >> $GITHUB_OUTPUT
          fi
      - name: Get skip_notification_check variable
        id: skip_notification_check
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "SKIP_NOTIFICATION_CHECK=${{ inputs.skip_notification_check }}" >> $GITHUB_OUTPUT
          else
            echo "SKIP_NOTIFICATION_CHECK=false" >> $GITHUB_OUTPUT
          fi
      - name: Check variables
        run: |
          echo "NOTIFICATION ENABLED: ${{ steps.send_notification.outputs.SEND_NOTIFICATION }}"
          echo "SKIP NOTIFICATION CHECK: ${{ steps.skip_notification_check.outputs.SKIP_NOTIFICATION_CHECK }}"

  scrape-singapore:
    needs:
      - general-setup
    uses: './.github/workflows/run-scraper.yml'
    secrets: inherit
    with:
      node_env: staging
      branch_name: ${{ github.sha }}
      skip_notification_check: ${{ needs.general-setup.outputs.skip_notification_check }}

  publish-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - general-setup
      - scrape-singapore
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "gh-pages"
      - uses: actions/download-artifact@v4
        with:
          name: data-${{ github.run_id }}

      - name: List `data` directory
        run: ls -l
      - name: Track file changes with git
        run: git status

  send-push-notifications:
    needs:
      - general-setup
      - scrape-singapore
      - publish-test
    uses: './.github/workflows/send-push-notifications.yml'
    if: needs.general-setup.outputs.send_notification == 'true'
    secrets: inherit
