name: scrape-test
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: yarn install
      - run: yarn build

      - name: Scrape data from ALL sources
        env:
          NODE_ENV: testing
          SERVER_URL: ${{ secrets.SERVER_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: yarn start

      - name: Send Push Notification
        if: success()
        env: 
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: yarn firebase