name: scrape-test

on:
  workflow_dispatch:
    inputs:
      send_notification:
        required: true
        type: boolean
        default: true
        description: 'Send push notification after scraping'

jobs:
  general-setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      send_notification: ${{ steps.send_notification.outputs.SEND_NOTIFICATION }}
    steps:
      - uses: actions/checkout@v4
      - name: Get send_notification variable
        id: send_notification
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "SEND_NOTIFICATION=${{ inputs.send_notification }}" >> $GITHUB_OUTPUT
          else
            echo "SEND_NOTIFICATION=true" >> $GITHUB_OUTPUT
          fi
      - run: |
          echo "NOTIFICATION ENABLED: ${{ steps.send_notification.outputs.SEND_NOTIFICATION }}"

  scrape-singapore:
    needs:
      - general-setup
    uses: './.github/workflows/run-scraper.yml'
    secrets: inherit
    with:
      node_env: staging
      branch_name: ${{ github.sha }}

  publish-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - general-setup
      - scrape-singapore
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "gh-pages"
      - uses: actions/download-artifact@v4
        with:
          name: data-${{ github.run_id }}

      - name: List `data` directory
        run: ls -l
      - name: Track file changes with git
        run: git status

  send-push-notification:
    runs-on: ubuntu-latest
    if: needs.general-setup.outputs.send_notification == 'true'
    needs:
      - general-setup
      - scrape-singapore
      - publish-test
    steps:      
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: './.github/actions/install-project-dependencies'

      - uses: actions/download-artifact@v4
        with:
          name: topics-${{ github.run_id }}
          path: temp
      - name: Check if `topics.json` exist
        id: check_file
        run: |
          if [ -f "temp/topics.json" ]; then
            echo "TOPICS_FILE_EXIST=true" >> $GITHUB_OUTPUT
            ls -l temp
          else
            echo "TOPICS_FILE_EXIST=false" >> $GITHUB_OUTPUT
            ls -l
          fi
      - run: |
          echo "temp/topics.json exist: ${{ steps.check_file.outputs.TOPICS_FILE_EXIST }}"

      - name: Send Push Notification
        if: steps.check_file.outputs.TOPICS_FILE_EXIST == 'true'
        run: yarn firebase
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
