name: scrape-test
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build

      - name: Scrape data from ALL sources
        env:
          NODE_ENV: testing
          SERVER_URL: ${{ secrets.SERVER_URL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: yarn start

      - name: Deploy to Github Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: output
          commit_message: 'chore: deploy to GitHub Pages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Push Notification
        if: success()
        env: 
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: yarn firebase